server:
  tomcat:
    uri-encoding: UTF-8
  address: 0.0.0.0
  port: 7001
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

sean:
  local-file:
    location: "D:\\file_repository\\"

# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.edu.tyut.sea2.module.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
